 # Ant
# Build your Java projects and run tests with Apache Ant.
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

#pool:
#  vmImage: ubuntu-latest

pool:
      name: Default
      Demands:
      - agent.name -equals "michVS2019"

variables:
- name: AGENT_USE_NODE10
  value: true
- name: SPECIFIC_JDK
  value: C:\Program Files\Java\jdk-11.0.12
#  value: C:\Program Files\Java\jdk-16.0.2

steps:

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'SQ9'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'ant-sample'
    cliProjectName: 'ant-sample'
    cliSources: 'src'
    extraProperties: |
      sonar.java.binaries=build


- task: Ant@1
  inputs:
    buildFile: 'build.xml'
    options: '-v'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkUserInputDirectory: 'C:\Program Files\Java\jdk1.8.0_181'

- task: PowerShell@2
  displayName: "Use specific JDK"
  inputs:
    targetType: 'inline'
    script: |
      #$jdkPath = "C:\Program Files\Java\jdk1.8.0_181"
      $jdkPath = $env:SPECIFIC_JDK
      #Write-Host "##vso[task.setvariable variable=JAVA_HOME]$jdkPath"
      Write-Host "##vso[task.setvariable variable=JAVA_HOME]C:\Program Files\Java\jdk-11.0.12"

- task: SonarQubeAnalyze@4