 # Ant
# Build your Java projects and run tests with Apache Ant.
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- name: AGENT_USE_NODE10
  value: true
- name: JAVA_HOME
  value: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64

steps:

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'SQ8'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'ant-sample'
    cliProjectName: 'ant-sample'
    cliSources: 'src'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.java.binaries=build
      # sonar.java.libraries=lib/*.jar
- task: Ant@1
  inputs:
    buildFile: 'build.xml'
    options: 
    targets: 'clean build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'

#- task: CmdLine@2
#  inputs:
#    script: 'export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64'

- task: SonarQubeAnalyze@4